export const INTERNAL_CODE_OK = 1
export const INTERNAL_CODE_BAD_REQUEST = -1
export const INTERNAL_CODE_EMPTY_LIST = 2
export const INTERNAL_CODE_NOT_REGISTER = -3
export const INTERNAL_CODE_NOT_USER_ACTIVE = -4

export const ERROR_CODE_OK = 0
export const ERROR_CODE_BAD_REQUEST = 100
export const ERROR_CODE_SERVICES = 101
export const ERROR_CODE_SIGN_IN = 102
export const ERROR_CODE_NOT_REGISTER = 104
export const ERROR_CODE_NOT_USER_ACTIVE = 105

